### ISSUE TITLE
exception "create conversation error"

### ISSUE THREAD

**Issue by kilinnik** [yinanrong/Mirror.ChatGpt#1]
I followed your example and got a "create conversation error" exception  public static async Task<string> RequestChatGPT(string prompt)
        {
            var services = new ServiceCollection();
            const string token = Token;
            services.AddBingClient(new() { Token = token });
            var app = services.BuildServiceProvider();
            var service = app.GetRequiredService<BingClient>();
            var chatCts = new CancellationTokenSource();
            //Set timeout by CancellationTokenSource
            chatCts.CancelAfter(TimeSpan.FromMinutes(5));
            var res = await service.ChatAsync(new(prompt), chatCts.Token);
            return res.Text;
        }

**Comment by yinanrong** [comment]
Hi @kilinnik ,sorry for replying late. Did you set a global proxy in your operating system ? As I know,Microsoft will prevent response if you use a proxy to request for new conversation and a null response content will be responsed.
