### ISSUE TITLE
A child repo.

### ISSUE THREAD

**Issue by liaosunny123** [yinanrong/Mirror.ChatGpt#2]
Hello!
I find this nuget cannot work commonly. However, I find the codes which needs fix is so large and I want to add more fuction.  
So I create a new repo https://github.com/liaosunny123/BingChatApi.
According to your Apacha 2.0, I have mark the codes from here which are modified and mark this repo url in the README.
I want to submit this issue to ask if anything else should be marked in the README?

**Comment by yinanrong** [comment]
Hi,you need to do nothing.
You can feel free to use the source code .
